### ISSUE TITLE
麦克风 不好用

### ISSUE THREAD

**Issue by Oneton429** [yuppiesnotzhuhao/Hackintosh-Dell-Inspiron-5548#1]
麦克风不好用
我现在很纠结，您的applealc声音大但是麦不好用
我之前的efi用的voodoohda麦克风可用但是外放声音小
问一下怎么办(选择哪个用)

**Comment by yuppiesnotzhuhao** [comment]
你好，我的5548麦克风硬件有问题，不能收音，没法做测试
