### ISSUE TITLE
安装时总是出错

### ISSUE THREAD

**Issue by LaoFengLaiLe** [yuppiesnotzhuhao/Hackintosh-Dell-Inspiron-5548#3]
可不可以问一下你的BIOS是怎么设置的，我安装的时候总是出错
![IMG_20200518_162834](https://user-images.githubusercontent.com/65520543/82217877-a5b73400-994d-11ea-91ea-8ee47ac547d4.jpg)

**Comment by yuppiesnotzhuhao** [comment]
请使用黑果小兵镜像中自带的config进行安装，安装完成后再替换为我的config

**Comment by LaoFengLaiLe** [comment]
需要更换成那个HD5500的吗

**Comment by yuppiesnotzhuhao** [comment]
对的

**Comment by LaoFengLaiLe** [comment]
那我明天试一下，谢谢大佬

**Comment by lzyjojo** [comment]
请问您的问题解决了吗
