### ISSUE TITLE
是否有OpenCore版本及热补丁?

### ISSUE THREAD

**Issue by Gaoyunhao** [yuppiesnotzhuhao/Hackintosh-Dell-Inspiron-5548#5]
目前我自己用的Opencore0.59版本，里面触控板I2C和电池热补丁搞不定，其余比较完美。谁帮忙搞一下热补丁?

**Comment by AhDaii** [comment]
大佬可以分享下opencore的efi吗，一起研究下

**Comment by Gaoyunhao** [comment]
> 大佬可以分享下opencore的efi吗，一起研究下

看我主页，我上传好了，最好一起解决问题吧，我的触控板和电池都驱动没搞定。

**Comment by sail9708** [comment]
> > 大佬可以分享下opencore的efi吗，一起研究下
> 
> 看我主页，我上传好了，最好一起解决问题吧，我的触控板和电池都驱动没搞定。
你好，请问一下你的装完之后，连接高分屏的时候，缩放由超过1080p的分辨率可以选择么？还有请问一下，声卡我把所有的layoutid都试了一遍，都不行，您知道可能是什么原因么？？
谢谢！

**Comment by sail9708** [comment]
> > 大佬可以分享下opencore的efi吗，一起研究下
> 
> 看我主页，我上传好了，最好一起解决问题吧，我的触控板和电池都驱动没搞定。

你好，请问一下你的装完之后，连接高分屏的时候，缩放由超过1080p的分辨率可以选择么？还有请问一下，声卡我把所有的layoutid都试了一遍，都不行，您知道可能是什么原因么？？
谢谢！

**Comment by Gaoyunhao** [comment]
> > > 大佬可以分享下opencore的efi吗，一起研究下
> 
> > 
> 
> > 看我主页，我上传好了，最好一起解决问题吧，我的触控板和电池都驱动没搞定。
> 
> 
> 
> 你好，请问一下你的装完之后，连接高分屏的时候，缩放由超过1080p的分辨率可以选择么？还有请问一下，声卡我把所有的layoutid都试了一遍，都不行，您知道可能是什么原因么？？
> 
> 谢谢！

好久没搞给苹果了。高分屏不行，进去卡8个苹果然后花屏，不知道怎么解开显存锁，刷BIOS也失败了。。音频那个，确认别的设置对了，多试几次，我的是17。建议最好先用clover搞好了换成OC。

**Comment by sail9708** [comment]
> > > > 大佬可以分享下opencore的efi吗，一起研究下
> > 
> > 
> > > 
> > 
> > 
> > > 看我主页，我上传好了，最好一起解决问题吧，我的触控板和电池都驱动没搞定。
> > 
> > 
> > 你好，请问一下你的装完之后，连接高分屏的时候，缩放由超过1080p的分辨率可以选择么？还有请问一下，声卡我把所有的layoutid都试一遍，都不行，您知道可能是什么原因么？？
> > 谢谢！
> 
> 高分屏不行，进去卡8个苹果然后花屏，不知道怎么解开显存锁，刷BIOS也失败了。。音频那个，确认别的设置对了，多试一次，我的是17。建议最好先用clover搞好了换成OC。

好的，感谢

**Comment by yuppiesnotzhuhao** [comment]
> 目前我自己用的Opencore0.59版本，里面触控板I2C和电池热补丁搞不定，其余比较完美。谁帮忙搞一下热补丁?

完善到什么程度了

**Comment by sail9708** [comment]
> > 目前我自己用的Opencore0.59版本，里面触控板I2C和电池热补丁搞不定，其余比较完美。谁帮忙搞一下热补丁?
> 
> 完善到什么程度了

我现在用的是0.63版本的oc，除了电池和声卡，其余都正常

**Comment by yuppiesnotzhuhao** [comment]
> > > 目前我自己用的Opencore0.59版本，里面触控板I2C和电池热补丁搞不定，其余比较完美。谁帮忙搞一下热补丁?
> > 
> > 
> > 完善到什么程度了
> 
> 我现在用的是0.63版本的oc，除了电池和声卡，其余都正常

你QQ多少？我i们一起完善一下

**Comment by yuppiesnotzhuhao** [comment]
> > > > 大佬可以分享下opencore的efi吗，一起研究下
> > 
> > 
> > > 
> > 
> > 
> > > 看我主页，我上传好了，最好一起解决问题吧，我的触控板和电池都驱动没搞定。
> > 
> > 
> > 你好，请问一下你的装完之后，连接高分屏的时候，缩放由超过1080p的分辨率可以选择么？还有请问一下，声卡我把所有的layoutid都试了一遍，都不行，您知道可能是什么原因么？？
> > 谢谢！
> 
> 好久没搞给苹果了。高分屏不行，进去卡8个苹果然后花屏，不知道怎么解开显存锁，刷BIOS也失败了。。音频那个，确认别的设置对了，多试几次，我的是17。建议最好先用clover搞好了换成OC。

你QQ多少？我们一起完善一下

**Comment by sail9708** [comment]
> > > > 目前我自己用的Opencore0.59版本，里面触控板I2C和电池热补丁搞不定，其余比较完美。谁帮忙搞一下热补丁?
> > > 
> > > 
> > > 完善到什么程度了
> > 
> > 
> > 我现在用的是0.63版本的oc，除了电池和声卡，其余都正常
> 
> 你QQ多少？我i们一起完善一下

876211428

**Comment by Gaoyunhao** [comment]
> > > > > 目前我自己用的Opencore0.59版本，里面触控板I2C和电池热补丁搞不定，其余比较完美。谁帮忙搞一下热补丁?
> > > > 
> > > > 
> > > > 完善到什么程度了
> > > 
> > > 
> > > 我现在用的是0.63版本的oc，除了电池和声卡，其余都正常
> > 
> > 
> > 你QQ多少？我i们一起完善一下
> 
> 876211428

大佬们,电池热补丁有完成的吗?还有触控板.

**Comment by yuppiesnotzhuhao** [comment]
> > > > > > 目前我自己用的Opencore0.59版本，里面触控板I2C和电池热补丁搞不定，其余比较完美。谁帮忙搞一下热补丁?
> > > > > 
> > > > > 
> > > > > 完善到什么程度了
> > > > 
> > > > 
> > > > 我现在用的是0.63版本的oc，除了电池和声卡，其余都正常
> > > 
> > > 
> > > 你QQ多少？我i们一起完善一下
> > 
> > 
> > 876211428
> 
> 大佬们,电池热补丁有完成的吗?还有触控板.

加楼上QQ，让他发你
