### ISSUE TITLE
开机有一定几率进入Dell的Diagnostic模式

### ISSUE THREAD

**Issue by Darkloid** [yuppiesnotzhuhao/Hackintosh-Dell-Inspiron-5548#6]
首先感谢大佬的efi，除麦克风外其余都能正常使用。（扬声器的声音似乎有点小）

我的问题是，有时候开机出现Dell的logo后屏幕一闪（蓝色），然后就会进入Dell的Diagnostic工具，如果不及时按下关机键就要开始自检了。我不清楚为什么会这样，也没有找到触发它的特定条件。但是重启后一般都会正常引导。

此外，有很小的几率进入系统后声卡用不了，但是重启可以解决这一问题。

**Comment by yuppiesnotzhuhao** [comment]
1、确实会有开机进自检的问题，暂时无解
2、声卡失效的问题我没有遇到，现在5548已经不是我的常用设备，你可以尝试更换声卡id以解决此问题

**Comment by Darkloid** [comment]
哈哈，5548也是我的备用设备了，第一次装黑苹果拿这个开刀。感谢大佬回复。
