### ISSUE TITLE
你好10.13.6系统上wifi驱动不管用，可以给出提示意见么

### ISSUE THREAD

**Issue by kai1991** [yuppiesnotzhuhao/Hackintosh-Dell-Inspiron-5548#8]
大佬你好，我电脑原装未改动灵越5548，用你的EFI完美安装了BigSur，但是实际使用中很卡顿，而且经常进入电脑自检程序，所以用你的EFI安装了10.13.6版本，但是发现wifi并不能向BigSur版本一样可以使用，我尝试了一下解决，但是并没有发现好的方法，希望可以帮我分析一下问题可以么？

问题：

1. 10.13.6版本中wifi不能使用，BigSur版本wifi正常
2. 黑苹果安装完后，电脑偶尔开机时就进入自检

感谢大佬！！！！

**Comment by yuppiesnotzhuhao** [comment]
开机进自检我无法解决。你的无线网卡是什么？

**Comment by kai1991** [comment]
> 开机进自检我无法解决。你的无线网卡是什么？

你好，我无线网卡已经驱动了，将所有的内核更新了，就好了。
**你的这个工程，让我的老电脑还能继续服役一段时间，再次感谢！！！**
